### PR TITLE
Pyodide 0.24 Release Notes

### PR DESCRIPTION
**Pull request by hoodmane**
@rth @ryanking13 

I guess we should make some performance benchmarks...

### CODE REVIEW

**Review by ryanking13 — APPROVED** [review]
Thanks @hoodmane for writing release notes!

I added some micropip improvements. If the wording is weird, feel free to modify them.

**Comment by hoodmane** [comment]
Thanks @ryanking13! The whole thing needs an edit, I'll go through and try to tighten it up hopefully tomorrow.

**Comment by rth** [comment]
Thanks, @hoodmane and @ryanking13 for these notes (and for doing all the work) ! It looks great!

re benchmarks: well yeah maybe if we had some JS/PY benchmarks we could have shown them, but it's also not that obvious what kind of benchmarks are representative of typical usage conditions, so it's a longer-term effort. And all the load time benchmarking is rather tricky as well. So overall I think as long as people can find the benchmarks that were done in PRs liked from the changelog it's probably enough.

**Comment by hoodmane** [comment]
Ok. Especially because we've taken so long to make this release already.

**Pull request merged**
